name: Deploy to VPS Hostinger

on:
  push:
    branches: [ "main" ] # Se activa solo al hacer push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚀 Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Entrar a la carpeta del proyecto
            cd ~/pms-zafiro-backend
            
            # 1. Bajar los últimos cambios de GitHub
            git pull origin main
            
            # 2. Reconstruir y reiniciar los contenedores (sin borrar datos)
            docker compose up -d --build
            
            # 3. Limpiar imágenes viejas para no llenar el disco
            docker image prune -f